default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: development_courses
test:
  <<: *default
  database: test_courses
